config:
  environments:
    baseline:
      target: "https://3v5sfjxbhhk2jzk4khsuslw56q0qwghl.lambda-url.us-west-2.on.aws"
    crossRegionLambdaInvoke:
      target: "https://6j4jcoo4h7op4t5ndnvblh2hrq0tjjcg.lambda-url.us-east-1.on.aws"
    crossRegionDDBGetItem:
      target: "https://kkb6d3y2wvvwfahb7xc5syow6i0rdhnv.lambda-url.us-west-2.on.aws"
    crossRegionLambdaInvokeWithCloudFront:
      target: "https://d38xwhn2pjj0b4.cloudfront.net"
  target: "bleh"
  phases:
    - duration: 300
      arrivalRate: 1
      rampTo: 5
      name: Warm up
scenarios:
  - name: 'POST_1kb'
    flow:
      - post: 
          url: /?id=1kb
  # - name: 'GET_1kb'
  #   flow:
  #     - get: 
  #         url: /?id=1kb
  # - name: 'POST_350kb'
  #   flow:
  #     - post: 
  #         url: /?id=350kb
  # - name: 'GET_1kb'
  #   flow:
  #     - get: 
  #         url: /?id=350kb